version: "3.9"

services:
  cache-redis:
    image: redis:alpine
    hostname: cache-redis
    container_name: cache-redis
    restart: on-failure
    ports:
      - '6379:6379'
    expose:
      - '6379'
    command: redis-server